feat: precompile contracts compatibility
axiomesh/axiom-ledger pull request #294
Opened 2024-01-09 08:59 UTC by hyf1223

2024-01-10 09:07 UTC, ywh254 requested changes

2024-01-10 09:07 UTC, ywh254 commented on internal/executor/system/native_vm.go
> +	//*vm.Message{}
注释去掉

2024-01-10 09:07 UTC, ywh254 commented on internal/executor/system/common/common.go
> +	//Run(*vm.Message) (*vm.ExecutionResult, error)
删了吧

2024-01-10 09:07 UTC, ywh254 commented on internal/executor/system/common/common.go
>  	EstimateGas(*types.CallArgs) (uint64, error)
EstimateGas也不要好了    和那个RunNativeVM函数类似   也搞个函数外面能直接调用好了

2024-01-10 09:07 UTC, ywh254 commented on internal/executor/system/common/common.go
> +	RequiredGas([]byte) uint64
这两个函数不用单独写    直接写那个PrecompileContract接口好了

2024-01-10 09:07 UTC, ywh254 commented on internal/executor/system/native_vm_test.go
> +			IsExpectedErr: true,
case为啥要改啊

2024-01-12 06:14 UTC, hyf1223 commented on internal/executor/system/native_vm.go
> +	//*vm.Message{}
已修复

2024-01-12 06:14 UTC, hyf1223 commented on internal/executor/system/common/common.go
> +	//Run(*vm.Message) (*vm.ExecutionResult, error)
已修复

2024-01-12 06:16 UTC, hyf1223 commented on internal/executor/system/native_vm.go
> +	ethcommon "github.com/ethereum/go-ethereum/common"
格式化之后就是这样的

2024-01-12 06:33 UTC, hyf1223 commented on internal/executor/system/common/common.go
> +	RequiredGas([]byte) uint64
已修复

2024-01-12 07:03 UTC, hyf1223 commented on internal/executor/system/native_vm_test.go
> +			IsExpectedErr: true,
对原来的run函数的逻辑做了一点优化

2024-01-12 07:04 UTC, hyf1223 commented on internal/executor/system/common/common.go
>  	EstimateGas(*types.CallArgs) (uint64, error)
已修复

2024-01-12 07:21 UTC, ywh254 requested changes

2024-01-12 07:21 UTC, ywh254 commented on internal/executor/system/native_vm.go
> +	//executionResult = &vm.ExecutionResult{
去掉

2024-01-12 07:21 UTC, ywh254 commented on internal/executor/system/common/common.go
> +	Reset(uint64, ledger.StateLedger, ethcommon.Address, *ethcommon.Address)
参数前面加上name

2024-01-12 07:24 UTC, hyf1223 commented on internal/executor/system/native_vm.go
> +	//executionResult = &vm.ExecutionResult{
已修复

2024-01-12 07:24 UTC, hyf1223 commented on internal/executor/system/common/common.go
> +	Reset(uint64, ledger.StateLedger, ethcommon.Address, *ethcommon.Address)
已修复

2024-01-12 08:45 UTC, ywh254 approved these changes

2024-01-12 08:45 UTC, merged